#!/bin/bash

#Have to run locally form within directory for safest operation (relative paths in app.js)

#Start production versions
export NODE_ENV=production

cd ryukyu_social_backend_prod/user_management
pm2 start app.js --name ryukyu_users_service_prod --env production

cd ../../ryukyu_social_backend_prod/user_photos
pm2 start app.js --name ryukyu_user_photos_service_prod --env production

cd ../../ryukyu_social_backend_prod/project_photos
pm2 start app.js --name ryukyu_project_photos_service_prod --env production

cd ../../ryukyu_social_backend_prod/projects
pm2 start app.js --name ryukyu_projects_service_prod --env production

cd ../../ryukyu_social_backend_prod/tasks
pm2 start app.js --name ryukyu_tasks_service_prod --env production

cd ../../ryukyu_social_backend_prod/user_profile
pm2 start app.js --name ryukyu_user_profile_service_prod --env production

cd ../../ryukyu_social_backend_prod/files
pm2 start app.js --name ryukyu_files_service_prod --env production

cd ../../ryukyu_social_backend_prod/code_checker
pm2 start app.js --name ryukyu_code_checker_service_prod --env production

#pm2 start ryukyu_social_backend_prod/task_puller_chatwork/app.rb --name ryukyu_task_puller_chatwork --interpreter ruby
#pm2 start ryukyu_social_backend_prod/task_puller_slack/app.rb --name ryukyu_task_puller_slack --interpreter ruby
